import { useState, useEffect } from "react";
import { Settings as SettingsIcon, Save, Sliders, MonitorUp, Key } from "lucide-react";
import { motion } from "motion/react";

export default function Settings() {
  const [delay, setDelay] = useState("5");
  const [agentUrl, setAgentUrl] = useState("");
  const [agentToken, setAgentToken] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetch('/api/settings')
      .then(res => res.json())
      .then(data => {
        const d = data.find((x: any) => x.key === 'typing_delay')?.value;
        if (d) setDelay(d);
        
        const url = data.find((x: any) => x.key === 'local_agent_url')?.value;
        if (url) setAgentUrl(url);
        
        const token = data.find((x: any) => x.key === 'local_agent_token')?.value;
        if (token) setAgentToken(token);
        
        setLoading(false);
      });
  }, []);

  const handleSave = async () => {
    setSaving(true);
    await fetch('/api/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key: 'typing_delay', value: delay })
    });
    
    await fetch('/api/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key: 'local_agent_url', value: agentUrl })
    });
    
    await fetch('/api/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key: 'local_agent_token', value: agentToken })
    });
    
    setSaving(false);
  };

  return (
    <div className="space-y-8 font-mono">
      <div className="border-b border-cyan-500/20 pb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-widest uppercase holo-text flex items-center gap-3">
            <SettingsIcon className="w-8 h-8" />
            System Configuration
          </h2>
          <p className="text-cyan-500/70 mt-2 uppercase text-sm tracking-wider">Global Parameters & Hardware Adjustments</p>
        </div>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-panel rounded-xl p-6 relative overflow-hidden"
      >
        <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/5 blur-[50px] pointer-events-none" />
        
        <div className="flex items-center gap-3 mb-6 border-b border-cyan-500/20 pb-4">
          <Sliders className="w-5 h-5 text-cyan-400" />
          <h3 className="text-lg font-bold uppercase tracking-widest text-cyan-300">Operation Parameters</h3>
        </div>
        
        {loading ? (
          <div className="animate-pulse h-12 bg-cyan-950/30 rounded border border-cyan-500/20"></div>
        ) : (
          <div className="space-y-8 relative z-10">
            <div>
              <label className="block text-sm uppercase tracking-widest font-bold text-cyan-400 mb-2">
                Simulated Processing Delay (Max Seconds)
              </label>
              <p className="text-sm text-cyan-500/70 mb-4 max-w-2xl leading-relaxed">
                To maintain stealth and human-like operation, E.V. introduces a random latency interval up to this maximum value prior to transmitting a response vector over Telegram.
              </p>
              <div className="flex items-center gap-4 max-w-sm">
                <input
                  type="number"
                  min="1"
                  max="60"
                  value={delay}
                  onChange={(e) => setDelay(e.target.value)}
                  className="w-full px-4 py-3 bg-cyan-950/40 border border-cyan-500/40 text-cyan-100 rounded focus:outline-none focus:border-cyan-300 focus:shadow-[0_0_15px_rgba(6,182,212,0.2)] font-mono text-lg"
                />
                <span className="text-cyan-500 uppercase tracking-widest text-sm font-bold">SEC</span>
              </div>
            </div>

            <div className="pt-6 border-t border-cyan-500/20">
              <div className="flex items-center gap-3 mb-6">
                <MonitorUp className="w-5 h-5 text-cyan-400" />
                <h3 className="text-lg font-bold uppercase tracking-widest text-cyan-300">Local PC Link (ngrok)</h3>
              </div>
              <p className="text-sm text-cyan-500/70 mb-6 max-w-2xl leading-relaxed">
                Provide the ngrok public URL and Security Token generated by your local Python agent. This allows the cloud brain to send commands directly to your personal computer.
              </p>
              
              <div className="space-y-4 max-w-2xl">
                <div>
                  <label className="block text-xs uppercase tracking-widest font-bold text-cyan-500 mb-2">
                    Agent Public URL (e.g. https://xyz.ngrok-free.app)
                  </label>
                  <input
                    type="text"
                    value={agentUrl}
                    onChange={(e) => setAgentUrl(e.target.value)}
                    placeholder="https://"
                    className="w-full px-4 py-3 bg-cyan-950/40 border border-cyan-500/40 text-cyan-100 rounded focus:outline-none focus:border-cyan-300 focus:shadow-[0_0_15px_rgba(6,182,212,0.2)] font-mono"
                  />
                </div>
                
                <div>
                  <label className="block text-xs uppercase tracking-widest font-bold text-cyan-500 mb-2 flex items-center gap-2">
                    <Key className="w-3 h-3" /> Security Token
                  </label>
                  <input
                    type="password"
                    value={agentToken}
                    onChange={(e) => setAgentToken(e.target.value)}
                    placeholder="Enter security token..."
                    className="w-full px-4 py-3 bg-cyan-950/40 border border-cyan-500/40 text-cyan-100 rounded focus:outline-none focus:border-cyan-300 focus:shadow-[0_0_15px_rgba(6,182,212,0.2)] font-mono"
                  />
                </div>
              </div>
            </div>
            
            <div className="pt-6 border-t border-cyan-500/20 flex justify-end">
              <button
                onClick={handleSave}
                disabled={loading || saving}
                className="inline-flex items-center gap-2 px-6 py-3 bg-cyan-950/50 text-cyan-300 border border-cyan-500/50 rounded hover:bg-cyan-900/80 transition-all uppercase tracking-widest text-sm hover:shadow-[0_0_20px_rgba(6,182,212,0.4)] disabled:opacity-50 font-bold"
              >
                <Save className="w-4 h-4" />
                {saving ? 'Applying...' : 'Apply Configuration'}
              </button>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
}
